name: CI

on: [push]

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

env:
  MAINNET_RPC: ${{ secrets.MAINNET_RPC }}
  SEPOLIA_RPC: ${{ secrets.SEPOLIA_RPC }}

jobs:
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --frozen-lockfile --network-concurrency 1

      - name: Precompile using 0.8.14 and via-ir=false
        run: yarn build

      - name: Run tests
        shell: bash
        run: yarn test:unit

  integration-tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1.2.0
        with:
          version: nightly

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --frozen-lockfile --network-concurrency 1

      - name: Precompile contracts
        run: yarn build

      - name: Run tests
        run: yarn test:integration

      - name: Ensure gas snapshots were updated
        run: git diff --exit-code -- .forge-snapshots/

  lint:
    name: Static Analysis
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: wagoid/commitlint-github-action@v5

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'yarn'

      - name: Install bulloak 
        uses: baptiste0928/cargo-install@v3
        with:
          crate: bulloak

      - name: Install dependencies
        run: yarn --frozen-lockfile --network-concurrency 1

      - name: Run forge-fmt && solhint
        run: yarn lint:check

      - name: Run bulloak check
        run: yarn lint:bulloak

      - name: Ensure auto-generated smocks are up to date
        run: yarn smock && git diff --exit-code -- test/smock

      - name: Run natspec-smells
        run: yarn lint:natspec 2>&1 >/dev/null | grep 'No issues found'
